teacher-profiles/config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

teacher-profiles/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

teacher-profiles/app/models/teacher.rb
class Teacher < ApplicationRecord
end

teacher-profiles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

teacher-profiles/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end
end

teacher-profiles/app/helpers/application_helper.rb
module ApplicationHelper
end

teacher-profiles/app/helpers/teachers_helper.rb
module TeachersHelper
end

teacher-profiles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherProfiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

teacher-profiles/app/views/teachers/index.html.erb
<h1>Listing Teachers</h1>
 
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
    </tr>
  </thead>
 
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.id %></td>
        <td><%= teacher.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New teacher", new_teacher_path %>