classrooms/config/routes.rb
Rails.application.routes.draw do
  resources :classroom_students
  resources :classrooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

classrooms/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

classrooms/app/models/classroom.rb
require_relative '../../client.rb'
class Classroom < ApplicationRecord
  has_many :classroom_students

  def teacher
    Client.teacher(teacher_id)
  end
end

classrooms/app/models/classroom_student.rb
require_relative '../../client.rb'
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom

  def student
    Client.student(student_id)
  end
end

classrooms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

classrooms/app/controllers/classroom_students_controller.rb
class ClassroomStudentsController < ApplicationController
  def index
    @classroom_students = ClassroomStudent.all
  end
end

classrooms/app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = Classroom.all
  end
end

classrooms/app/helpers/application_helper.rb
module ApplicationHelper
end

classrooms/app/helpers/classroom_students_helper.rb
module ClassroomStudentsHelper
end

classrooms/app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

classrooms/app/views/classroom_students/index.html.erb
<h1>Listing Classroom Students</h1>
 
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Classroom Name</th>
      <th>Student Name</th>
    </tr>
  </thead>
 
  <tbody>
    <% @classroom_students.each do |classroom_student| %>
      <tr>
        <td><%= classroom_student.id %></td>
        <td><%= classroom_student.classroom.name %></td>
        <td><%= classroom_student.student.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New classroom student", new_classroom_student_path %>

classrooms/app/views/classrooms/index.html.erb
<h1>Listing Classrooms</h1>
 
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Classroom Name</th>
      <th>Teacher Name</th>
    </tr>
  </thead>
 
  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.id %></td>
        <td><%= classroom.name %></td>
        <td><%= classroom.teacher.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New classroom", new_classroom_path %>

classrooms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classrooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>