student-profiles/config/routes.rb
Rails.application.routes.draw do
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

student-profiles/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

student-profiles/app/models/student.rb
class Student < ApplicationRecord
end

student-profiles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

student-profiles/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
end

student-profiles/app/helpers/application_helper.rb
module ApplicationHelper
end

student-profiles/app/helpers/students_helper.rb
module StudentsHelper
end

student-profiles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentProfiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

student-profiles/app/views/students/index.html.erb
<h1>Listing Students</h1>
 
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
    </tr>
  </thead>
 
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= student.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New student", new_student_path %>